[project]
name = "auto-job-search-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "bs4>=0.0.2",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "selenium>=4.34.2",
]
